apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  RABBITMQ_USER: {{ .Values.secrets.values.RABBITMQ_USER | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.values.RABBITMQ_PASSWORD | quote }}
  SMTP_USER: {{ .Values.secrets.values.SMTP_USER | quote }}
  SMTP_PASS: {{ .Values.secrets.values.SMTP_PASS | quote }}
  SMTP_HOST: {{ .Values.secrets.values.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.secrets.values.SMTP_PORT | quote }}
  SMTP_FROM: {{ .Values.secrets.values.SMTP_FROM | quote }}
