apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  RABBITMQ_USER: {{ .Values.secrets.values.RABBITMQ_USER | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.values.RABBITMQ_PASSWORD | quote }}
  SMTP_USER: {{ .Values.secrets.values.SMTP_USER | quote }}
  SMTP_PASS: {{ .Values.secrets.values.SMTP_PASS | quote }}
