secrets:
    name: ENC[AES256_GCM,data:J7hwvTrzYMrEGpC3MA==,iv:hceRZBs7xMGY2HlIv0NmnHjc7t1ONYUF7zE0D5rVp7s=,tag:mCA8HKPMTP8qcO4PwQKBvQ==,type:str]
    values:
        RABBITMQ_USER: ENC[AES256_GCM,data:OS5gA0LYIHU=,iv:ITa9W0WXLAuVJ3PNzas+ftBTjj6Jx3VbEJYXepWOJOc=,tag:+FAvy+8gzJnUfO+NyLCWxA==,type:str]
        RABBITMQ_PASSWORD: ENC[AES256_GCM,data:RZgILADVJJc=,iv:aqkbWLLq3ULeg2w4xXIo7+VccnqyTR//o+lCO/CsKdA=,tag:4JZ5XNHXC0tpGBzOP18C7Q==,type:str]
        SMTP_USER: ENC[AES256_GCM,data:gFr4nZ8XiRk=,iv:gvaZKiDDpvVkXMfcwjalU8BZoKvqOphzbjakwhmvptA=,tag:Zv1g3FtTO2Scv6uM4gGdYQ==,type:str]
        SMTP_PASS: ENC[AES256_GCM,data:mJC5n1GUHks=,iv:sTohGTvm8awetF5R6A+jTZd9NlOqWvKl+yMHjme9IOk=,tag:o6rSV3S53Ua12GT9cH0zCg==,type:str]
sops:
    age:
        - recipient: age1a4v75pwnnanfr6rk3nvc4vpk7zy2tr4pt0qtfehssmw5f3ct899q593fad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRHlWOHIvVVNsWnVPNDVD
            WWRPby9EM1hrdzMwTHg0bW9xMEMxQUNGV1UwCm44UVJGNDZzZDRHT3RGb0ZEVnNE
            RVFqeDV6K29lcDVFNE15Uk1aRkFCQlEKLS0tIHFqQVU1aWcwZFo1NXc4OUF2dDEy
            REZ4RXIrYkd6dStNZEpTLzB5WXZaMGMKgPczTwOZDnoGyjZEkZO8AajBtcMF1yq8
            SKBMM4MvCM811isaXvZGaDceIqdcTUsnsmTzMAyzCOGDh3nNHYFYbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T19:18:43Z"
    mac: ENC[AES256_GCM,data:gpQMlA0k21QScF0v9yEO2psIr4g4KJYQ1O58FbIfaxg3B9n/xCX/ob6YOPAbCT5FH2VqXe67J8H5fJIvTEzj7IK5GWNP4cDw142Qv4BnEp8v8dBYiKPEwqs82rxgK/WvHqTCBV9KGy2swm2BM4eK2yxnHN9ATtIhLId8eOQFAlg=,iv:jM8A4wtW3nIOqzkbckv+sV/lnJNNPX22NJrKsrqXJOo=,tag:GY5CjYG4HXu6kP34XGjnww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
