namespace: email

email:
  name: email-app
  image:
    repository: ghcr.io/cloudnativedevelopmentteamh/focusboard/email
    tag: latest
  replicas: 1
  smtp:
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    from: "noreply@focusboard.app"
  configmap:
    name: app-config

rabbitmq:
  host: "rabbitmq.auth.svc.cluster.local"
  port: 5672
